Tf documentation
ethantang95/DIGITS-GAN pull request #4
Opened 2017-06-09 22:28 UTC by ethantang95

2017-06-09 22:31 UTC, ethantang95 commented
@timzaman @gheinrich for review, or should we have a meeting and discuss about this? Thanks

2017-06-16 18:09 UTC, TimZaman requested changes
Some changes needed

2017-06-16 18:09 UTC, TimZaman commented on docs/GettingStartedTensorflow.md
> +# Getting Started with Tensorflow 1.1 in DIGITS
remove 1.1

2017-06-16 18:09 UTC, TimZaman commented on docs/BuildTensorflow.md
> +# Installing Tensorflow
Tensorflow->TensorFlow and add ™ when it makes sense.

2017-06-16 18:09 UTC, TimZaman commented on docs/BuildTensorflow.md
> +DIGITS is current targetting Tensorflow-gpu V1.1.
"Tensorflow-gpu" to "Tensorflow 1.1.0rc0"

2017-06-16 18:09 UTC, TimZaman commented on docs/BuildTensorflow.md
>  > NOTE: Tensorflow support is still experimental!
remove

2017-06-16 18:09 UTC, TimZaman commented on docs/BuildTensorflow.md
>  DIGITS now supports Tensorflow as an optional alternative backend to Caffe or Torch.
remove

2017-06-16 18:09 UTC, TimZaman commented on docs/GettingStartedTensorflow.md
> +{insert image here}
add

2017-06-16 18:09 UTC, TimZaman commented on docs/GettingStartedTensorflow.md
> +*
star?

2017-06-16 18:09 UTC, TimZaman commented on docs/GettingStartedTensorflow.md
> +    @model_propertyOther Tensorflow Tools in DIGITS
~Other Tensorflow *~

2017-06-16 18:09 UTC, TimZaman commented on docs/GettingStartedTensorflow.md
> +For example, this is what it looks like for LeNet:
for a LeNet-5 model, with LeNet-5 clickable to http://yann.lecun.com/exdb/lenet/

2017-06-16 18:09 UTC, TimZaman commented on docs/GettingStartedTensorflow.md
> +nclasses      | number    | Number of classes (for classification datasets). For other type of datasets, this is undefined
nclasses -> `nclasses`
and do for the rest of the table properties too

2017-06-16 18:09 UTC, TimZaman commented on docs/GettingStartedTensorflow.md
> +__init()__    | None        | The constructor for the ```UserModel``` class
double dunders do not render! also use backticks

2017-06-16 18:09 UTC, TimZaman commented on docs/GettingStartedTensorflow.md
> +__init()__    | None        | The constructor for the ```UserModel``` class
init-> `__init__`

2017-06-16 18:09 UTC, TimZaman commented on docs/GettingStartedTensorflow.md
> +__init()__    | None        | The constructor for the ```UserModel``` class
also for the other methods (!)

2017-06-16 18:09 UTC, TimZaman commented on docs/GettingStartedTensorflow.md
> +### Internal Properties
Properties -> Methods, everywhere

2017-06-16 18:09 UTC, TimZaman commented on docs/GettingStartedTensorflow.md
> +Function Name       | Parameters          | Description
All function names should have backtics

2017-06-16 18:09 UTC, TimZaman commented on docs/GettingStartedTensorflow.md
> +Function Name       | Parameters          | Description
Also add backtics to parametrs like:
pred - the images (..) -> `pred` - the images (..)

2017-06-16 18:09 UTC, TimZaman commented on docs/GettingStartedTensorflow.md
> +TensorBoard is a visualization tools provided by Tensorflow to see the graph of your neural network. DIGITS provides easy access to TensorBoard for your network while creating it. The TensorBoard can
tools-> tool

2017-06-16 18:09 UTC, TimZaman commented on docs/GettingStartedTensorflow.md
> +
Add:
_Experimental functionality._

2017-06-16 18:09 UTC, TimZaman commented on docs/GettingStartedTensorflow.md
> +{insert image here}
+

2017-06-16 18:09 UTC, TimZaman commented on docs/GettingStartedTensorflow.md
> +{insert image of tensorboard here}
+

2017-06-16 18:09 UTC, TimZaman commented on docs/GettingStartedTensorflow.md
> +
+add one sentence what this does.

2017-06-16 18:09 UTC, TimZaman commented on docs/GettingStartedTensorflow.md
> +For example, this is what it looks like for LeNet:
+ add 2 sentences what the below model does (classification of hand written characters to which character it belongs to)

2017-06-16 18:09 UTC, TimZaman commented on docs/GettingStartedTensorflow.md
> +```python
put 5-10 sentences on how this works and how exactly one uses this: train your thing, model is saved, make a new model, point to the saved thing, then change the weight names you dont want, etc.

2017-06-16 18:09 UTC, TimZaman commented on docs/GettingStartedTensorflow.md
> +### Multi-GPU Training
remove

2017-06-16 18:09 UTC, TimZaman commented on docs/BuildTensorflow.md
> +## Installation From Source
no no no no

2017-06-16 18:09 UTC, TimZaman commented on docs/BuildTensorflow.md
> +## Basic Installation
~Basic~

2017-06-19 21:17 UTC, TimZaman approved these changes
Nice!

2017-06-19 21:18 UTC, TimZaman commented
Why does the travis build fail?

2017-06-19 21:57 UTC, ethantang95 commented
numpy updated to v 1.13 and it broke stuff, it's fixed on master. The other is just linting

2017-06-19 22:42 UTC, TimZaman commented
Make sure to keep the CI happy - even the linter.

2017-06-21 18:20 UTC, merged